name: rss
dependencies:
- python=2.7.10=0
- python-dateutil=2.4.2=py27_0
- pytz=2015.4=py27_0
- pyyaml=3.11=py27_1
- readline=6.2=2
- requests=2.8.1=py27_0
- six=1.9.0=py27_0
- wheel=0.26.0
- yaml=0.1.6=0
- zlib=1.2.8=0
- pip:
  - bitarray==0.8.1
  - feedparser==5.2.1
  - pybloom==1.1
